### ISSUE TITLE
I wonder what "ref","src","trg"represent for

### ISSUE THREAD

**Issue by AlterWW14** [KU-CVLAB/MIDMs#6]
In Sketch and Reference work,what do they mean?
"ref":Exempular
"src":Condition
"trg":psedo-ground truth?
By the way,what does psedo-Ground truth exactly means?Color image paired with sketch?

**Comment by j0seo** [comment]
"ref" : exemplar
"src" pseudo-ground truth e.g., color image paired with sketch(trg)
"trg": condition
Thank you for showing interest in our work!
