### ISSUE TITLE
I goota a problem when running code

### ISSUE THREAD

**Issue by AlterWW14** [KU-CVLAB/MIDMs#7]
how can I get this file?
![PZ2$31UY6{{O0~L)4GXPZE8](https://user-images.githubusercontent.com/88940349/213103811-544bb91b-bee3-4c2f-87d8-0894d70165cd.png)

**Comment by j0seo** [comment]
I'm sorry for the inconvenience. You can download from https://github.com/microsoft/CoCosNet/blob/master/util/color150.mat
I will check this issue and add this file. Thank you!

**Comment by AlterWW14** [comment]
> 

Thanks for answering
